## NUMPY ARRAY OPERATIONS

In [26]:
import numpy as np

In [27]:
arr=np.array([1,2,3,4,5])
print("basic slicing: ",arr[0:3])
print("with step: ",arr[0:5:2])
print("negative slicing: ",arr[-5])

basic slicing:  [1 2 3]
with step:  [1 3 5]
negative slicing:  1


In [28]:
arr_2d= np.array([[1,2,3], #oth row
                  [4,5,6],#1st row
                  [7,8,9]]) #2nd row
print("specific element:", arr_2d[1,2])
#this is done only in numpy not in normal python
print("specific row:", arr_2d[0]) #0th row all columns
print("specific column:", arr_2d[:,1]) #all rows 2nd column

specific element: 6
specific row: [1 2 3]
specific column: [2 5 8]


## SORTING

In [29]:
unsorted = np.array([3,7,1,9,4])
sorted_arr = np.sort(unsorted)
print("Unsorted array:", unsorted)
print("Sorted array:", sorted_arr) # sorting

arr_2d= np.array([[3,1],[1,2],[2,3]])
print("sorted 2d array by column:\n", np.sort(arr_2d, axis=0)) #sort along columns

Unsorted array: [3 7 1 9 4]
Sorted array: [1 3 4 7 9]
sorted 2d array by column:
 [[1 1]
 [2 2]
 [3 3]]


## FILTERING

In [30]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers%2==0]
print("Even numbers:", even_number)

Even numbers: [ 2  4  6  8 10]


# Filter with mask

In [31]:
mask=numbers>5
print("numbers greater than 5: ",numbers[mask])

numbers greater than 5:  [ 6  7  8  9 10]


## FANCY INDEXING VS np.where()

In [32]:
indices = [0,2,4]
print("Fancy indexing result:", numbers[indices])

where_result = np.where(numbers > 5)
print("Indices from np.where():", where_result)
print("NP where",numbers[where_result])

Fancy indexing result: [1 3 5]
Indices from np.where(): (array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


In [33]:
conditin_array=np.where(numbers>5,numbers*2,numbers)
print(conditin_array)

[ 1  2  3  4  5 12 14 16 18 20]


In [34]:
conditin_array=np.where(numbers>5,"True","False")
print(conditin_array)

['False' 'False' 'False' 'False' 'False' 'True' 'True' 'True' 'True'
 'True']


### ADDING AND REMOVING DATA

In [35]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
combined=np.concatenate((arr1,arr2)) #always use concatenate function to combine arrays
print("Combined array:", combined)

Combined array: [1 2 3 4 5 6]


# ARRAY COMPATIBILITY

In [36]:
a=np.array([1,2,3])
b=np.array([4,5,6])
C=np.array([7,8,9])
print("compatibility shapes",a.shape==b.shape)

compatibility shapes True


In [ ]:
original=np.array([[1,2],[3,4]])
new_row=np.array([[5,6]])

with_new_row=np.vstack((original,new_row))#stack array in sequence vertically(vstack is used)
print(original)
print("With new row:",with_new_row)

new_col= np.array([[7],[8],[9]])
with_new_col=np.hstack((with_new_row,new_col)) #stack array in sequence horizontally(hstack is used)
print("With new column:",with_new_col)

[[1 2]
 [3 4]]
With new row: [[1 2]
 [3 4]
 [5 6]]
With new column: [[1 2 7]
 [3 4 8]
 [5 6 9]]


# delete array

In [43]:
arr=np.array([1,2,3,4,5])
deleted_array=np.delete(arr,2) #deleting element at index 2
print("Original array:",deleted_array)

Original array: [1 2 4 5]
