In [13]:
import numpy as np
print('numpy', np.__version__)


numpy 2.1.2


## LEARING NUMPY

In [14]:
import numpy as np

## CREATING PYTHON FROM LIST

In [15]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr_1d)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr_2d)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


In [16]:
py_list = [7, 8, 9, 10]
print("Python List:", py_list*2)

Python List: [7, 8, 9, 10, 7, 8, 9, 10]


In [17]:
py_array = [1,2,3,4,5]
print("Python Array:", py_array*2)

Python Array: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [18]:
np_array =np.array([1,2,3,4,5])
print("Python Array:", np_array*2)

Python Array: [ 2  4  6  8 10]


In [19]:
import time
start=time.time() ##for exact tine calculation
py_list=[i*2 for i in range(1000000)]
print("Time taken by Python list:", time.time()-start)
start=time.time()
np_array=np.arange(1000000)*2
print("Time taken by Numpy array:", time.time()-start)

Time taken by Python list: 0.08000826835632324
Time taken by Numpy array: 0.0050160884857177734


## CREATING PYTHON FROM SCRATCH

In [20]:
zeros=np.ones((3,4))  ##creating array of ones/zeros/three
print("Array of Zeros:\n", zeros)

full=np.full((2,2),7) 
print("Array of Full:\n", full)

random = np.random.random((2,3))
print("Array of Randoms:\n", random)

Array of Zeros:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Array of Full:
 [[7 7]
 [7 7]]
Array of Randoms:
 [[0.06693233 0.42474376 0.5203913 ]
 [0.31736102 0.87071263 0.13543349]]


In [21]:
sequence= np.arange(0,10,2) ## exclusive output
print(sequence)

[0 2 4 6 8]


## VECTOR , MATRIX AND TENSOR

In [26]:
vector=np.array([1,2,3,4])
print(vector)

matrix= np.array([[1,2,3,4],[4,5,6,7]])
print(matrix)

tensor=np.array([[[1,2],[3,4]],[
                  [5,6],[7,8]]])
print("tensor: ",tensor)

[1 2 3 4]
[[1 2 3 4]
 [4 5 6 7]]
tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## PROPERTIES OF ARRAY

In [30]:
arr=np.array([[1,2],[3,4]])
print("array:",arr)

print("shape: ",arr.shape)
print("dimension: ",arr.ndim)
print("size: ",arr.size)
print("datatype: ",arr.dtype)

array: [[1 2]
 [3 4]]
shape:  (2, 2)
dimension:  2
size:  4
datatype:  int64


## ARRAY RESHAPING , RESIZING , FLATTENED AND TRANSPOSE

In [36]:
arr=np.arange(12)
print("original array: ",arr)

reshaped=arr.reshape((3,4))
print("reshaped: ",reshaped)

flattened= reshaped.flatten()
print("flattend: ",flattened)

#ravel returns view,instead of copy
raveled=reshaped.ravel()
print("ravel: ",raveled)

transpose=reshaped.T
print("transposed: ",transpose)



original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattend:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
ravel:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
transposed:  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
